import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { Loader2 } from 'lucide-react';
import type { TablesInsert } from '@/integrations/supabase/types';

const supplierSchema = z.object({
  name: z.string().min(2, 'Nome é obrigatório'),
  phone: z.string().min(10, 'Telefone inválido'),
  email: z.string().email('Email inválido'),
  manager_name: z.string().min(2, 'Nome do gerente/responsável é obrigatório'),
});

type SupplierFormData = z.infer<typeof supplierSchema>;

interface SupplierFormProps {
  onSuccess: () => void;
  initialData?: Partial<SupplierFormData> & { id?: string; code?: string };
}

export function SupplierForm({ onSuccess, initialData }: SupplierFormProps) {
  const [loading, setLoading] = useState(false);

  const form = useForm<SupplierFormData>({
    resolver: zodResolver(supplierSchema),
    defaultValues: {
      name: initialData?.name || '',
      phone: initialData?.phone || '',
      email: initialData?.email || '',
      manager_name: initialData?.manager_name || '',
    },
  });

  const onSubmit = async (data: SupplierFormData) => {
    setLoading(true);

    let error;

    if (initialData?.id) {
      const result = await supabase
        .from('suppliers')
        .update(data)
        .eq('id', initialData.id);
      error = result.error;
    } else {
      // code is auto-generated by database trigger
      const insertData = {
        ...data,
        code: '', // will be overwritten by trigger
      } as TablesInsert<'suppliers'>;
      const result = await supabase.from('suppliers').insert([insertData]);
      error = result.error;
    }

    if (error) {
      toast.error('Erro ao salvar fornecedor');
      console.error(error);
    } else {
      toast.success(initialData?.id ? 'Fornecedor atualizado!' : 'Fornecedor criado!');
      onSuccess();
    }

    setLoading(false);
  };

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
        {initialData?.code && (
          <div className="p-3 bg-muted rounded-md">
            <span className="text-sm text-muted-foreground">Código: </span>
            <span className="font-mono font-semibold">{initialData.code}</span>
          </div>
        )}

        <FormField
          control={form.control}
          name="name"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Nome do Fornecedor</FormLabel>
              <FormControl>
                <Input placeholder="Nome da empresa" {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />

        <FormField
          control={form.control}
          name="phone"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Telefone</FormLabel>
              <FormControl>
                <Input placeholder="(11) 99999-9999" {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />

        <FormField
          control={form.control}
          name="email"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Email</FormLabel>
              <FormControl>
                <Input type="email" placeholder="email@exemplo.com" {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />

        <FormField
          control={form.control}
          name="manager_name"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Gerente/Responsável</FormLabel>
              <FormControl>
                <Input placeholder="Nome do responsável" {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />

        <div className="flex justify-end gap-3 pt-4">
          <Button type="submit" disabled={loading}>
            {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            {initialData?.id ? 'Salvar Alterações' : 'Criar Fornecedor'}
          </Button>
        </div>
      </form>
    </Form>
  );
}
